### PR TITLE
ST6RI-298: Show nested ports in a compartment

### PR DESCRIPTION
**Pull request by himi**
Provides an option to show nested ports in a compartment.
Please update PlantUML to the latest version,  "1.1.25.202012030239" / "1.2020.14.himi5"

In Jupyter environment, --style comptree option is added:

PortTestJupyter

### CODE REVIEW

**Review by seidewitz — CHANGES_REQUESTED** [review]
It needs to be possible to do this in the Eclipse environment, too. The capabilities shouldn't differ.

**Comment by himi** [comment]
Oh, I'd need to enhance PlantUML-Eclipse side for your request...  That's my laziness and will work on it.  Please wait.

**Comment by himi** [comment]
Ready.  Now the style menu items have check marks to toggle styles.  Please update PlantUML to the latest version

**Comment by seidewitz** [comment]
This looks good in Eclipse now. Thanks!

**Review by seidewitz — APPROVED** [review]

**Pull request merged**
