### PR TITLE
ST6RI-288 Refactor Jupyter installer

### PR DESCRIPTION
**Pull request by ivan-gomes**
# Changelog

* Jupyter installer refactored to its own Maven module `org.omg.sysml.jupyter.installer` so it can aggregate build artifacts across other modules, i.e. `org.omg.sysml.jupyter.kernel` and `org.omg.sysml.jupyter.jupyterlab`.
* The build artifacts of the new module `org.omg.sysml.jupyter.installer` are a zip, tar.gz, and directory structure that is ready to be copied to https://github.com/Systems-Modeling/SysML-v2-Release without manual post-processing. In other words it unzips its dependencies, filters out `sysml.library` to prevent duplication, and adds installer files (opinionated and automated to SST's preferences).
* The installer now incorporates installation of `org.omg.sysml.jupyter.jupyterlab` (JupyterLab extension) and switches to using JupyterLab from Jupyter Notebook. Feature parity with syntax highlighting, code folding, and line numbers were all verified and enabled by default. User prompt at the end of the installer now says to run `jupyter lab`.

# Future Scope

These are things that were scoped out (or confirmed to be out of scope) for this issue.

* Jupyter kernel conda packaging and publishing with conda-forge. In order to do this, the static (build) artifacts need to be published in a publicly accessible place that Conda Forge's CI can then download and package per our Conda spec. The download could be from a GitHub repo, e.g. SysML-v2-Release, or just about any static host, e.g. Bintray. Once this is merged in and the build artifacts have been published somewhere I can circle back to this, but I went ahead and implemented the `sysml.library` de-duplication in a more opinionated way so we don't get blocked on this Jupyter work.
* NPM publishing will be done in https://openmbee.atlassian.net/browse/ST6RI-291 in 2020-11 and the installer will be updated to  pull from there as part of the issue.

### CODE REVIEW

**Comment by seidewitz** [comment]
I get the following error when trying to do a clean re-build of the HEAD of the ST6RI-288 branch from the repo:

```
[INFO] --- exec-maven-plugin:3.0.0:exec (gradle-prepare-package) @ jupyter-sysml-kernel ---

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find org.omg.sysml:org.omg.sysml.interactive:0.5.0-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/omg/sysml/org.omg.sysml.interactive/0.5.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/omg/sysml/org.omg.sysml.interactive/0.5.0-SNAPSHOT/org.omg.sysml.interactive-0.5.0-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/org/omg/sysml/org.omg.sysml.interactive/0.5.0-SNAPSHOT/org.omg.sysml.interactive-0.5.0-SNAPSHOT-all.jar
       - file:/Users/seidewitz/.m2/repository/org/omg/sysml/org.omg.sysml.interactive/0.5.0-SNAPSHOT/maven-metadata.xml
       - file:/Users/seidewitz/.m2/repository/org/omg/sysml/org.omg.sysml.interactive/0.5.0-SNAPSHOT/org.omg.sysml.interactive-0.5.0-SNAPSHOT.pom
       - file:/Users/seidewitz/.m2/repository/org/omg/sysml/org.omg.sysml.interactive/0.5.0-SNAPSHOT/org.omg.sysml.interactive-0.5.0-SNAPSHOT-all.jar
     Required by:
         project :
```

**Comment by ivan-gomes** [comment]
> I get the following error when trying to do a clean re-build of the HEAD of the ST6RI-288 branch from the repo:
> 
> ```
> [INFO] --- exec-maven-plugin:3.0.0:exec (gradle-prepare-package) @ jupyter-sysml-kernel ---
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':shadowJar'.
> > Could not resolve all dependencies for configuration ':runtimeClasspath'.
>    > Could not find org.omg.sysml:org.omg.sysml.interactive:0.5.0-SNAPSHOT.
>      Searched in the following locations:
>        - https://repo.maven.apache.org/maven2/org/omg/sysml/org.omg.sysml.interactive/0.5.0-SNAPSHOT/maven-metadata.xml
>        - https://repo.maven.apache.org/maven2/org/omg/sysml/org.omg.sysml.interactive/0.5.0-SNAPSHOT/org.omg.sysml.interactive-0.5.0-SNAPSHOT.pom
>        - https://repo.maven.apache.org/maven2/org/omg/sysml/org.omg.sysml.interactive/0.5.0-SNAPSHOT/org.omg.sysml.interactive-0.5.0-SNAPSHOT-all.jar
>        - file:/Users/seidewitz/.m2/repository/org/omg/sysml/org.omg.sysml.interactive/0.5.0-SNAPSHOT/maven-metadata.xml
>        - file:/Users/seidewitz/.m2/repository/org/omg/sysml/org.omg.sysml.interactive/0.5.0-SNAPSHOT/org.omg.sysml.interactive-0.5.0-SNAPSHOT.pom
>        - file:/Users/seidewitz/.m2/repository/org/omg/sysml/org.omg.sysml.interactive/0.5.0-SNAPSHOT/org.omg.sysml.interactive-0.5.0-SNAPSHOT-all.jar
>      Required by:
>          project :
> ```

Any chance you're doing a `mvn package` instead of a `mvn install`? The refactor includes making `dist/sysmli.jar` a first class build artifact of `org.omg.sysml.interactive` as `org.omg.sysml.interactive-${version}-all.jar` and `org.omg.sysml.jupyter.kernel` depends on that build artifact as installed in the local Maven repo. `mvn package` doesn't install into local Maven repo, but `mvn install` does. This keeps the Maven -> Gradle hand-off clean, but if it's a problem we may be able to work around it so `mvn package` still succeeds.

**Comment by ivan-gomes** [comment]
Should work with only `mvn package` now as of https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/166/commits/1876b12346c4502d612ecdcfbdf238e4a4db127b.

**Comment by seidewitz** [comment]
Oops, you're right, I had it configured to automatically do a `mvn package`. I tried it with `install` and it worked. I am not sure it really matters -- I just didn't think to try it with `install` before. But I can pull the latest and try it again with `package`.

**Comment by seidewitz** [comment]
I can confirm that the build now works again using `mvn package`. And, after building, I was able to run the installer and get through "Step 5: Installing SysML Jupyter kernel". However, "Step 6: Installing JupyterLab extension for SysML" failed because I didn't have Node.js installed. After installing Node.js, I was able to complete the installation and (for the first time!) run Jupyter Lab. I then openned and interacted with a SysML notebook, confirming that the kernel was functioning.

I believe this now provides an end-to-end test of the installation on MacOS. 

However, it also points out that the associated README needs to be updated to reflect the installation of Jupyter Lab. In particular, the need for Node.js should be mentioned (unless the installer can be updated to install it automatically as necessary) and the final step in the instructions should be to change to run `jupyter lab` instead of `jupyter notebook`. 

This needs to be added to the work to complete this task.

**Comment by blake-regalia** [comment]
I believe the only reason it needs Node.js is to use `yarn` to install packages. From this perspective, Node.js can be seen as a dependency of yarn, so rather than requiring Node.js I would suggest simply requiring yarn be installed.

**Comment by miyakowilson** [comment]
I got a FileNotFoundError for a uml file, but the file exists.
After run mvn clean then build, install.bat in ...\org.omg.sysml.jupyter.installer\target\org.omg.sysml.jupyter.installer-0.6.0-SNAPSHOT as admin.
Here is the output.

--- Step 1: Testing Conda installation ---
C:\ProgramData\Anaconda3\Library\bin\conda.bat
C:\ProgramData\Anaconda3\Scripts\conda.exe
conda 4.8.5
--- Step 2: Testing Java installation ---
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
--- Step 3: Installing dependencies into Conda environment ---
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - jupyterlab=2
    - python=3


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.9.1                |   py38haa95532_0         2.9 MB
    openssl-1.1.1g             |       he774522_0         4.8 MB
    ------------------------------------------------------------
                                           Total:         7.7 MB

The following packages will be UPDATED:

  conda              conda-forge::conda-4.8.5-py38h32f6830~ --> pkgs/main::conda-4.9.1-py38haa95532_0

The following packages will be SUPERSEDED by a higher-priority channel:

  openssl                                       conda-forge --> pkgs/main



Downloading and Extracting Packages
conda-4.9.1          | 2.9 MB    | ############################################################################ | 100%
openssl-1.1.1g       | 4.8 MB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

--- Step 4: Testing Python installation ---
C:\ProgramData\Anaconda3\python.exe
--- Step 5: Installing SysML Jupyter kernel ---
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-kernelspec-script.py", line 9, in <module>
    sys.exit(KernelSpecApp.launch_instance())
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\kernelspecapp.py", line 268, in start
    return self.subapp.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\kernelspecapp.py", line 195, in start
    path = self.kernel_spec_manager.remove_kernel_spec(kernel_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 288, in remove_kernel_spec
    shutil.rmtree(spec_dir)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 615, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 613, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\ProgramData\\Anaconda3\\share\\jupyter\\kernels\\sysml\\isysml-2020-06-all\\model\\Export\\Track_2_-_Requirements_V_V.Use_Cases_and_Example_Models.Usage_Focused_Modeling_Example.1-Vehicle_Example-Usage_Focused_Modeling_Approach.2-Featires.4-Ports.N-Ary_Connectors.User_Defined_Stereotypes.profile.uml'
<string>:137: DeprecationWarning: replace is ignored. Installing a kernelspec always replaces an existing installation
Removing existing kernelspec in C:\ProgramData\Anaconda3\share\jupyter\kernels\sysml
Traceback (most recent call last):
  File "C:\Users\mw107\Documents\GitHub\SST\org.omg.sysml.jupyter.installer\target\org.omg.sysml.jupyter.installer-0.6.0-SNAPSHOT\\install.py", line 28, in <module>
    exec(open(os.path.join(kernel_dir, 'install.py')).read())
  File "<string>", line 137, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 343, in install_kernel_spec
    shutil.rmtree(destination)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 615, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 613, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\ProgramData\\Anaconda3\\share\\jupyter\\kernels\\sysml\\isysml-2020-06-all\\model\\Export\\Track_2_-_Requirements_V_V.Use_Cases_and_Example_Models.Usage_Focused_Modeling_Example.1-Vehicle_Example-Usage_Focused_Modeling_Approach.2-Featires.4-Ports.N-Ary_Connectors.User_Defined_Stereotypes.profile.uml'
Failed with error #1.
Press any key to continue . . .

**Comment by miyakowilson** [comment]
I deleted the files from "C:\ProgramData\Anaconda3\share\jupyter\kernels\sysml\isysml-2020-06-all\model\Export" manually and run install.bat again.
Then I got the below error.

--- Step 1: Testing Conda installation ---
C:\ProgramData\Anaconda3\Library\bin\conda.bat
C:\ProgramData\Anaconda3\Scripts\conda.exe
conda 4.9.1
--- Step 2: Testing Java installation ---
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
--- Step 3: Installing dependencies into Conda environment ---
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

--- Step 4: Testing Python installation ---
C:\ProgramData\Anaconda3\python.exe
--- Step 5: Installing SysML Jupyter kernel ---
[RemoveKernelSpec] Removed C:\ProgramData\Anaconda3\share\jupyter\kernels\sysml
<string>:137: DeprecationWarning: replace is ignored. Installing a kernelspec always replaces an existing installation
Traceback (most recent call last):
  File "C:\Users\mw107\Documents\GitHub\SST\org.omg.sysml.jupyter.installer\target\org.omg.sysml.jupyter.installer-0.6.0-SNAPSHOT\\install.py", line 28, in <module>
    exec(open(os.path.join(kernel_dir, 'install.py')).read())
  File "<string>", line 137, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 345, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 552, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\mw107\\Documents\\GitHub\\SST\\org.omg.sysml.jupyter.installer\\target\\org.omg.sysml.jupyter.installer-0.6.0-SNAPSHOT\\sysml'
Failed with error #1.
Press any key to continue . . .

**Comment by miyakowilson** [comment]
I modified install.py in 
...\org.omg.sysml.jupyter.installer\target\org.omg.sysml.jupyter.installer-0.6.0-SNAPSHOT\jupyter-sysml-kernel
line 137
os.path.join(os.path.dirname(os.path.abspath(__file__)), 'jupyter-sysml-kernel', 'sysml'),
line 151 to
local_kernel_json_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'jupyter-sysml-kernel','sysml', 'kernel.json')
and run install.bat, but failed in Step 6 about Node.js and npm.
So I downloaded Node js windows's installation version (Latest LTS Version: 14.15.0 (includes npm 6.14.8)).
Then I run install.bat and installed successfully.
Then run "jupyter lab" and I could run sysml2 syntax fine.

I tried to run %viz "1a-Parts Tree" but got an error:
Dot Executable: C:\Program File does not exist Cannnot find Graphviz.....
I have C:\Program Files\Graphviz 2.44.1\..
Do I need to do some configuration?

**Comment by seidewitz** [comment]
@ivan-gomes Please update your status on updating the READMEs and addressing the Windows installation issues today.

**Comment by ivan-gomes** [comment]
READMEs updated and numerous Windows related issues addressed - see individual commits for details. Installers handle Nodejs installation, so no addition to manual prerequisites necessary. Tested successfully on Windows. Should be ready to go.

**Comment by ivan-gomes** [comment]
Thanks for testing @miyakowilson. Seems like you had a number of potential issues: 1) https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/166#issuecomment-722565623 - bad pre-existing jupyter-sysml-kernel install indicated by `2020-06` in the path and the file path length that exceeds Window's 260 character limit, 2) https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/166#issuecomment-722573783 - Windows ignoring the change in current working directory (cwd) addressed by switching to a subprocess @ https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/166/commits/566de4fbf0dfcf00690897be33be54875a5ce734, 3) https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/166#issuecomment-723221578 - a custom Graphviz installation (not the one installed by the installer) taking precedence (likely because it is first in %PATH%) and its path having a space in it which is now handled in https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/166/commits/8d438ba2b3a0875d17841404699a284626a2f994. Hopefully you should be able to install it on your machine now.

**Comment by miyakowilson** [comment]
I did Marven clean, build and run install.bat as admin. But it failed.  
There is no  "C:\ProgramData\Anaconda3\share\jupyter\kernels\sysml" directory.
Here is console out.
--- Step 1: Testing Conda installation ---
C:\ProgramData\Anaconda3\Library\bin\conda.bat
C:\ProgramData\Anaconda3\Scripts\conda.exe
conda 4.9.1
--- Step 2: Testing Java installation ---
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
--- Step 3: Installing dependencies into Conda environment ---
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

--- Step 4: Testing Python installation ---
C:\ProgramData\Anaconda3\python.exe
--- Step 5: Testing Graphviz installation ---
C:\ProgramData\Anaconda3\Library\bin\dot.bat
C:\Program Files\Graphviz 2.44.1\bin\dot.exe
--- Step 6: Testing Node.js installation ---
C:\ProgramData\Anaconda3\node.exe
C:\Program Files\nodejs\node.exe
--- Step 7: Installing SysML Jupyter kernel ---
Couldn't find kernel spec(s): sysml
jupyter-sysml-kernel directory not found.
Failed with error #1.
Press any key to continue . . .

**Comment by miyakowilson** [comment]
After manually copied ..\target\org.omg.sysml.jupyter.installer-0.6.0-SNAPSHOT\jupyter-sysml-kernel\sysml to C:\ProgramData\Anaconda3\share\jupyter\kernels, commented out "call jupyter kernelspec remove sysml -f" from  install.bat, I could run jupyter lab successfully.  Then I parsed '1a-Parts Tree'.  I tried to test the plantUML with %viz "1a-Parts Tree" and I got an error. 
java.io.IOExcepation: The pipe has been ended.  Am I running plantUML correctly?  
I have Graphviz 2.44.1 version installed.
image

**Comment by himi** [comment]
@miyakowilson.  Just my guess.  I think GraphViz is not properly installed in your environment.  Can you try "dot -c" to initialize GraphViz?

**Comment by seidewitz** [comment]
@ivan-gomes 

I just noticed that you moved `SysML2.setup` under `org.omg.sysml.jupyter.installer`. We don't want to do this. `SysML2.setup` is the setup for the Oomph install of the development Eclipse environment. It should not be considered part of the Jupyter install.

I was not not expecting updates to be made to this file. Please let me know what what changed, if anything, and expect that the setup file will be moved back to the `org.omg.sysml.installer` project.

**Comment by miyakowilson** [comment]
Thanks Hisashi. After I did "dot -c", the jupyter lab show the diagram.

**Comment by seidewitz** [comment]
@miyakowilson 
But we still need to resolve why you had to do this:

> After manually copied `..\target\org.omg.sysml.jupyter.installer-0.6.0-SNAPSHOT\jupyter-sysml-kernel\sysml` to `C:\ProgramData\Anaconda3\share\jupyter\kernels`, commented out call `jupyter kernelspec remove sysml -f` from install.bat, I could run jupyter lab successfully.

**Comment by ivan-gomes** [comment]
> @ivan-gomes
> 
> I just noticed that you moved `SysML2.setup` under `org.omg.sysml.jupyter.installer`. We don't want to do this. `SysML2.setup` is the setup for the Oomph install of the development Eclipse environment. It should not be considered part of the Jupyter install.
> 
> I was not not expecting updates to be made to this file. Please let me know what what changed, if anything, and expect that the setup file will be moved back to the `org.omg.sysml.installer` project.
> 
> Update: As far as I can tell, there was no change to the `SysML2.setup` file. Therefore, unless there is some reason you need a copy in `org.omg.sysml.jupyter.installer`, I will be re-establishing the `org.omg.sysml.installer` project and moving the file back there.

This was unintentional and has been reverted in https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/166/commits/63db16f373ec042ca82ce2939faf7c3f1e296bf9.

**Comment by ivan-gomes** [comment]
> I did Marven clean, build and run install.bat as admin. But it failed.
> There is no "C:\ProgramData\Anaconda3\share\jupyter\kernels\sysml" directory.
> Here is console out.
> 
> ```
> --- Step 1: Testing Conda installation ---
> C:\ProgramData\Anaconda3\Library\bin\conda.bat
> C:\ProgramData\Anaconda3\Scripts\conda.exe
> conda 4.9.1
> --- Step 2: Testing Java installation ---
> C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
> java version "1.8.0_251"
> Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
> Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
> --- Step 3: Installing dependencies into Conda environment ---
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> # All requested packages already installed.
> 
> --- Step 4: Testing Python installation ---
> C:\ProgramData\Anaconda3\python.exe
> --- Step 5: Testing Graphviz installation ---
> C:\ProgramData\Anaconda3\Library\bin\dot.bat
> C:\Program Files\Graphviz 2.44.1\bin\dot.exe
> --- Step 6: Testing Node.js installation ---
> C:\ProgramData\Anaconda3\node.exe
> C:\Program Files\nodejs\node.exe
> --- Step 7: Installing SysML Jupyter kernel ---
> Couldn't find kernel spec(s): sysml
> jupyter-sysml-kernel directory not found.
> Failed with error #1.
> Press any key to continue . . .
> ```

Are you launching a Command Prompt as Admin manually and then executing `install.bat`? Can you please try just double clicking `install.bat` from the File Explorer - without running as admin? I'm suspecting that the working directory isn't being set as expected.

`Couldn't find kernel spec(s): sysml` is a red herring, not an issue. It's just the output of the command to remove any existing installation of the SysML kernel. I will commit a tweak to suppress it. The real error is `jupyter-sysml-kernel directory not found.`, which is the result of it not finding the directory relative to the current working directory.

**Comment by ivan-gomes** [comment]
Hi @miyakowilson, can you please update to the latest commit and try again? I was not able to recreate `jupyter-sysml-kernel directory not found.`, but I elaborated the error message to give us the full path so if it's still occurring we'll have more info in the output.

**Comment by miyakowilson** [comment]
The error not finding "jupyter-sysml-kernel" happened when I run the Install.bat in org.omg.sysml.jupyter.installer.   Sorry about that. 
When I run ...\org.omg.sysml.jupyter.installer\target\org.omg.sysml.jupyter.installer-0.6.0-SNAPSHOT\Install.bat, I could install it successfully.  The jupyter lab runs fine.  Then I copied the org.omg.sysml.jupyter.installer-0.6.0-SNAPSHOT.zip to new PC, install miniconda and run the installation.  But the installation stops (keep running) after --- Step 7: Installing SysML Jupyter kernel --- output.  I tested by unzipping with the original PC's different directory and the result are the same.

**Comment by seidewitz** [comment]
I got my Windows 10 VM up and tried running the installer, as of commit cf4d4f4. Once I rebuilt and ran from the correct place, it worked for me.

**Review by seidewitz — APPROVED** [review]

**Comment by seidewitz** [comment]
@miyakowilson 

> The error not finding `jupyter-sysml-kernel` happened when I run the `Install.bat` in org.omg.sysml.jupyter.installer.   Sorry about that. <br/>
> When I run `...\org.omg.sysml.jupyter.installer\target\org.omg.sysml.jupyter.installer-0.6.0-SNAPSHOT\Install.bat`, I could install it successfully.  The jupyter lab runs fine.  Then I copied the `org.omg.sysml.jupyter.installer-0.6.0-SNAPSHOT.zip` to new PC, install miniconda and run the installation.  But the installation stops (keep running) after `--- Step 7: Installing SysML Jupyter kernel ---` output.  I tested by unzipping with the original PC's different directory and the result are the same.

The Zip file does not include the `kerml`, `sysml` and `sysml.library` directories, and I believe the script was probably just doing a thorough directory search looking for these. I am going to be copying the unzipped installation directory to the release repository, which also has all the model file directories, so this shouldn't be a problem.

**Pull request merged**
