### PR TITLE
ST6RI-631: Show short names in compartments, hide empty subjects

### PR DESCRIPTION
**Pull request by himi**
This PR shows short names in compartments.

### CODE REVIEW

**Comment by himi** [comment]
```
part p0 {
  attribute <'A-1'> a1;
  attribute <A2> a2;
}

enum def E0 {
  <'Enum 0'> e0;
  <'Enum 1'> e1;
}
```
is rendered as:
image

**Comment by himi** [comment]
This PR also hides annoying empty subjects in compartments and cases.
For example, previously it visualized
```
requirement <'Req-2'> req2;
requirement req;
case c1;
```
as
image
.
By this PR, it does not show such subjects, and the example above is rendered as:
image

**Review by seidewitz — APPROVED** [review]

**Comment by Canvis-Me** [comment]
After this pull request, eclipse can generate hidden subject, however for jupyter lab it seems the empty subject still exists.

```
package hide_empty_sub {
    requirement <'Req-2'> req2;
    requirement req;
    case c1;
}
```
gets
jupyter-not-hide-empty-subject

**Comment by seidewitz** [comment]
> After this pull request, eclipse can generate hidden subject, however for jupyter lab it seems the empty subject still exists.

@himi 
Even after rebuilding with the latest development revision, this still seems to be the case. Any idea why?

**Comment by himi** [comment]
I did not find the root cause but in Jupyter environment I found subject.getName() returned `null` instead of `subj` and caused this issue.  I think I need to make a Jira issue for this.

**Comment by seidewitz** [comment]
I just created Jira issue ST6RI-667. You can still put it on the 2023-02 sprint if you think you can get it resolved by the end of next week.

**Comment by himi** [comment]
Sorry, I'm currently deadly busy and cannot work on this this month.

**Comment by seidewitz** [comment]
> Sorry, I'm currently deadly busy and cannot work on this this month.

OK, it's not critical. The issue is on the backlog.

**Pull request merged**
