### PR TITLE
ST6RI-541 Update implementation for 2022-05 baseline

### PR DESCRIPTION
**Pull request by seidewitz**
This pull request is entirely an abstract syntax update. 

1. _Annotation._ Made `owningAnnotatedElement` derived in the UML metamodel.
2. _Documentation._ Made `documentedElement` a subsetting of `Element::owner`, rather than a redefinition (similar to `TextualRepresentation::representedElement`).
3. _ConjugatedPortDefinition._
    - Removed previous hand-written could for `ConjugatedPortDefinitionImpl::getName`.
    - Implemented required naming by overriding `effectiveName` method.
4. _Feature._
    - Added `ownedFeatureInverting` property.
    - Corrected multiplicity of `chainingFeature` and `ownedFeatureChaining` from `1..*` to `0..*`.
5. _FeatureChaining._ Made `featureChained` a subsetting of `Relationship::owningRelatedElement`, rather than a redefinition.
6. _FeatureInverting._ New relationship. (Concrete syntax to be implemented under issue [ST6RI-544](https://openmbee.atlassian.net/browse/ST6RI-544).)
7. _FramedConcernMembership._ Made `kind` a redefinition. 
8. _RequirementVerificationMembership._ Made `kind` a redefinition. 

**Note:** Changes 1, 7 and 8 only effect the `SysML.uml` metamodel file. There is no change to the `SysML.ecore` metamodel or generated Java classes for these changes. (The `Annotation::owningAnnotatedElement` property was already being marked as derived in the Ecore metamodel by the custom UML importer, and the duplicate `kind` properties were being ignored.)

### CODE REVIEW

**Comment by seidewitz** [comment]
@ivan-gomes @manasbajaj 

The `SysML.uml` file on this branch is ready for generating the API.

**Review by ivan-gomes — CHANGES_REQUESTED** [review]
It looks like `RequirementConstraintMembership#kind` does not have a multiplicity specified (resulting in a default interpretation of `0..1`) while redefining `FramedConcernMembership#kind` has a multiplicity specified of `0..*`. This is resulting in a typing issue downstream in API work. I am assuming the desired multiplicity for `RequirementConstraintMembership#kind` is `0..*`, so could we please explicitly specify it as such in the XMI?

**Comment by seidewitz** [comment]
Ugh. 

Default multiplicity in UML is actually 1..1. All of these `kind` propertis should have default multiplicity 1..1 – `kind` is required to have a single value, and, for `FramedConcernMembership` and `RequirementVerificationMembership` the value is fixed as `requirement`. 

The multiplicity for `kind` got messed up in MagicDraw when the missing redefinition relationships for `kind` were added for this release. I have pushed an update that corrects this in the `SysML.uml` file.

**Comment by seidewitz** [comment]
Also, the pull-request build for this branch is failing with the following error.
```
[INFO] Resolving class path of MavenProject: org.omg.sysml:org.omg.sysml:0.24.0-SNAPSHOT @ /home/travis/build/Systems-Modeling/SysML-v2-Pilot-Implementation/org.omg.sysml/pom.xml

[ERROR] Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: 
Exception parsing OSGi MANIFEST /home/travis/.m2/repository/p2/osgi/bundle/com.ibm.icu/67.1.0.v20200706-1749/com.ibm.icu-67.1.0.v20200706-1749.jar: 
zip END header not found -> [Help 1]

org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: 
Exception parsing OSGi MANIFEST /home/travis/.m2/repository/p2/osgi/bundle/com.ibm.icu/67.1.0.v20200706-1749/com.ibm.icu-67.1.0.v20200706-1749.jar: zip END header not found
```

The normal branch build does not get this error, and I have not seen it on any other builds. The error is repeatable if the build is retriggered.

Any idea what is causing this?

(cc @himi)

**Comment by himi** [comment]
I've just noticed it :)  I'll look into it.

**Review by ivan-gomes — APPROVED** [review]

**Pull request merged**
