### PR TITLE
ST6RI-613: Update PlantUML to 1.2022.7.himi1

### PR DESCRIPTION
**Pull request by himi**
Update PlantUML by setting the dependent version to `1.2022.7.himi1`

### CODE REVIEW

**Comment by himi** [comment]
I found a critical bug in PlantUML-SysML2 and I updated it to `1.2022.7.himi2`

**Comment by seidewitz** [comment]
The compartment title styling is a nice improvement! However, would it be possible to put some space below the title, before the rest of the compartment contents? Probably about half the height of a blank line would be ideal, if that's possible.

**Comment by himi** [comment]
@seidewitz sorry.  I did not make skin parameters for that.  To change that, I'd need to move such formatting parameters to skin parameters.  (Actually, many creole formatting parameters are hardcoded).  I do not have sufficient time to work on that changes.

**Comment by seidewitz** [comment]
OK, it’s not critical.

**Comment by himi** [comment]
I should mention that such formatting are determined solely by PlantUML, not by SysMLv2-Pilot-Implementation side.  So I can update PlantUML to tune such formatting parameters later.

**Pull request merged**
