### PR TITLE
ST6RI-344 Automate markdown to pdf generation

### PR DESCRIPTION
**Pull request by capsulecorplab**
PR enables [pandoc/latex](https://github.com/pandoc/dockerfiles#pandoc-scripts) docker image to run pandoc commands in the `org.omg.sysml.site/build.sh` bash script for generating `org.omg.sysml.site/README.pdf` from `org.omg.sysml.site/README.md` and publishes output to `org.omg.sysml.site` branch using GitHub Actions, whenever a push is made to the `master` branch.

Example build stats for a [Build docs w/ Pandoc & Deploy Output to Branch](https://github.com/capsulecorplab/SysML-v2-Pilot-Implementation/runs/1977771107) job, as well as a [README.pdf](https://github.com/capsulecorplab/SysML-v2-Pilot-Implementation/commit/bf1a81cd1df635359e4fe32188c318391accb328#diff-1b7928c16c6bc006b502f1232ef09065a6e5ea2761cb229dca672ec6f746d79b) generated from build, can be previewed on the [org.omg.sysml.site](https://github.com/capsulecorplab/SysML-v2-Pilot-Implementation/tree/org.omg.sysml.site) branch of my [forked repo](https://github.com/capsulecorplab/SysML-v2-Pilot-Implementation).

Note: a deploy key and secret key will need to be generated and added into the [SysML-v2-Pilot-Implementation](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation) repo settings, in order for automated builds with GitHub Actions to trigger. See [Create SSH Deploy Key](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key)

### CODE REVIEW

**Comment by capsulecorplab** [comment]
Rebased branch off master and added following changes since b0e95c69227f1c70a1c589f4f5eadb60bb7c15ea:
- convert `README.md` to `README.adoc` in org.omg.sysml.site/ (see https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/210/commits/cc91b025a963ec00ffc37826de78c0ee712af5f9)
- generate `README.pdf` from `README.adoc` using `asciidoctor` (see https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/210/commits/3ae44b03590d623d56fd4696c0c2ac4df5d9a02e)

**Comment by ujhelyiz** [comment]
Yesterday during the SST call I have promised some examples about integrating the asciidoctor-maven-plugin for PDF generation. The official example for that is available in https://github.com/asciidoctor/asciidoctor-maven-examples/blob/main/asciidoctor-pdf-example

The more complex case with PDF generation I wanted to show is not openly available and in the VIATRA project we only use HTML generation (https://git.eclipse.org/c/viatra/org.eclipse.viatra.git/tree/documentation/org.eclipse.viatra.documentation.help/pom.xml)

**Comment by himi** [comment]
I do not fully follow the thread of this discussion but it seems to lack the maven script to automate the conversion from adoc to pdf.    Is someone working on it?

**Comment by himi** [comment]
OMG. I'm now busy with the integration work and I already migrated my environment to Eclipse 2021-03 and Tycho 2.3.0....  I need to restore my environment If you want me to work on it now.

**Comment by seidewitz** [comment]
This is PR not critical. It would just be nice to get it done, so we have a consistent approach to handling PDF documents, especially as we potentially move forward on other documentation.

@himi, if you get a POM updated for this in your revised environment, won't the same update essentially work in the current development environment? If so, once you've validated the update in your environment, you can just let me know how to update the POM and I can do it in the current environment. I just don't want to take the time right now myself to figure out how to use the asciidoctor plugin.

If it is doing that is going to be any trouble, though, we can just put this off again.

**Comment by himi** [comment]
OK.  I'll try to work by branching out from ST6RI-380 because my main environment is already on M1 Mac.

**Comment by ujhelyiz** [comment]
I have created a new branch https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/tree/ST6RI-340 in this repository that is merged into the latest master, replaced the remaining readme files and added the corresponding maven configuration.

However, it does not show up in this pull request as it is based on a branch from the mirror of @capsulecorplab I don't consider I have push right for. @seidewitz should I open a new pull request, or could you maybe update the 'from' branch of this PR to keep the changes together with the previous commits?

**Comment by capsulecorplab** [comment]
@ujhelyiz I would recreate the branch off 3ae44b0 then cherrypick your added commits

**Comment by ujhelyiz** [comment]
I have opened PR https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/235 from the branch (it started off from the head of this PR branch, so it already included everything).

**Pull request closed without merging**
