### PR TITLE
ST6RI-383 Transition implementation platform to Eclipse 2021-03 release and Java 11

### PR DESCRIPTION
**Pull request by seidewitz**
This pull request includes the following updates:

1. `org.omg.sysml.installer/SysML2.setup` has been updated to for the Eclipse 2021-03 release and Java 11. This has been tested for a clean install of a new Eclipse instance.
2. `travis.yml` has been updated for `openJDK11`.
3. `SysML-v2-Pilot-Implementation/pom.xml` has been updated to use Eclipse 2021-03.

Notes:

1. Most of the plugin MANIFEST.MF files had warnings that there was a dependency that required Java 11, but that the build execution environment was set to Java 8. Given the warning, I would prefer not to leave the Java 8 execution environment in the manifests, but I was not sure of the conclusion of the discussion on this in PR #232. Should the execution environment be set to Java 11 for all plugins, or is it acceptable to leave it unspecified?
2. No other changes have been made at this point to the top-level POM other than the change of the Eclipse version. It looks like the other changes made in PR #232 for ST6RI-380 (plugin version updates and platform environment) could probably be included in this PR without harm, but we could also just wait and merge them separately from PR #232.
3. As proposed by @himi for ST6RI-380, the `maven.compiler.source` and `maven.compiler.target` properties are still set at `1.8`. We need to come to a consensus on whether this is really consistent with moving our development environment to Java 11. At the very least, if we leave the Maven build at 1.8, then I think we need to set the "Compiler compliance level" to also be 1.8 in our Eclipse development configuration (it defaults to 11, of course, for Eclipse 2021-03).
4. I have not reviewed all the various READMEs yet for possible updates related to migrated to Eclipse 2021-03 and Java 11. However, we may want to complete PR #210 for ST6RI-344 before doing that.

### CODE REVIEW

**Comment by seidewitz** [comment]
@himi 
The Travis builds are failing due to the following errors:
```
Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'plantuml-eclipse' from location https://github.com/himi/p2-update-puml-sysmlv2/raw/main/updates: Unable to read repository at https://github.com/himi/p2-update-puml-sysmlv2/raw/main/updates/compositeContent.xml. peer not authenticated
```
This is not happening when I run the build locally.

**Comment by himi** [comment]
I recommend to merge ST6RI-380 or cherry-pick https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/232/commits/e81d6416a18f0dcc08e7c53a84f261bf7c993d41

**Review by himi — APPROVED** [review]

**Comment by himi** [comment]
I approved this PR, but recommend to update Tycho to 2.3.0 because many problems are fixed.  It's an option to defer it by ST6RI-380.

**Comment by seidewitz** [comment]
> I recommend to merge ST6RI-380 or cherry-pick [e81d641](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/commit/e81d6416a18f0dcc08e7c53a84f261bf7c993d41)

Cherry-picking e81d641 resolved the build problem.

**Pull request merged**
