### PR TITLE
ST6RI-384 Update implementation for 2021-05 metamodel baseline

### PR DESCRIPTION
**Pull request by seidewitz**
The following metaclasses have been added:

- OccurrenceDefinition
- OccurrenceUsage
- PortioningFeature
- PortionKind (enumeration)
- EventOccurrenceUsage _[added since original baseline]_

**Note:** The metaclass LifeClass was added to the normative abstract syntax in the 2021-05 baseline, but it already existed previously in the implementation.

The following metaclasses have been removed:

- IndividualDefinition
- IndividualUsage
- TimeSliceFeature
- SnapshotFeature

Other changes:

1. _Occurrences._ A basic textual syntax has been added for **`occurrence def`** and **`occurrence`**.  No syntax has been added for "events" or "messages" (that will be handled as part of ST6RI-385).
2. _Individuals._ The notations for **`individual def`**, **`individual`**, **`timeslice`** and **`snapshot`** are unchanged. However, it they now parse to OccurrenceDefinition and OccurrenceUsage (possibly with a PortioningFeature), rather than to IndividualDefinition and IndividualUsage. No syntax has been added for declaring more specific kinds of individuals like **`individual part`**, etc. (that will be handled as part of ST6RI-385).
3. _PlantUML._ Minimal updates have been made to PlantUML visualization to support the existing graphical notation for individuals using the new metamodel.
4. _ST6RI-368._ This bug has been resolved by renaming `Occurrences::successions` to `Occurrences::happensBeforeLinks` in the Kernel model library. `Transfers::flows` has also been renamed to `Transfers::transferBefores`.
5. _ST6RI-378._ This bug has been resolved by adding the base association `Occurrences::HappensLink` in the Kernel model library.

### CODE REVIEW

**Comment by seidewitz** [comment]
@himi
I actually did find a couple of cases of possible NPEs in the PlantUML-related code. These happen when the abstract syntax tree is ill-formed (like a FeatureTyping with no type), which can happen when Eclipse Xtext  editor incrementally parses text with syntax errors. I pushed a commit that fixes the cases I found.

**Review by himi — APPROVED** [review]
I modified just for code formatting and removed the warning.

**Comment by seidewitz** [comment]
@ivan-gomes 
During subsequent implementation, I found that I need to add one additional metaclass, EventOccurrenceUsage. I have added this class to the `SysML.uml` file on this branch. Please be sure to use the version of the file as of the latest commit (88cf2d0) for generation of the API code.

**Comment by conradbock** [comment]
Sorry for the delay.  The notes look OK, except I think you [decided ](https://openmbee.atlassian.net/browse/ST6RI-368?focusedCommentId=12636) Transfers::transferBefores should be transfersBefore.  Can you remind me how to see the kerml files that have these changes?

**Review by ivan-gomes — APPROVED** [review]
lgtm

**Comment by seidewitz** [comment]
@conradbock See the updates for commit cb71466.

**Comment by seidewitz** [comment]
@himi 
In order to get this PR closed, I pushed a commit fixing ST6RI-400, which was to be included on this branch. Please reply ASAP if you have any problem with the update.

**Pull request merged**
