### PR TITLE
ST6RI-520 Update implementation for 2022-03 baseline

### PR DESCRIPTION
**Pull request by seidewitz**
This pull requests implements significant updates to the abstract syntax for annotations and metadata, per the 2022-03 baseline metamodel. 

**Not Implemented**
1. The proposed semantic metadata/language extension mechanism. (This will be address in a future PR for ST6RI-521.)
2. Setting the value of the `annotatedElement` value(s) of a MetadataFeature instance. (This is potentially deferred until the full implementation of reflection for ST6RI-417.)

**Abstract Syntax**

_Metaclasses removed:_

1. Documentation (relationship)
3. AnnotatingFeature (renamed to MetadataFeature)
4. MetadataFeature
5. MetadataFeatureValue

_Metaclasses added:_

1. Documentation (as a subclass of Comment)
2. MetadataFeature (replaces AnnotatingFeature)
3. Metaclass
4. MetadataDefinition
6. MetadataUsage

_Metaclasses updated:_

1. AnnotatingElement – the implementation of `AnnotatingElement::annotedElement` has been updated so that, if the AnnotatingElement has not explicit Annotation relationships, the `owner` of the AnnotatingElement is returned as the `annotatedElement` (e.g., the `owningNamespace`, if the AnnotatingElement is an `ownedMember` of a Namespace).
2. Definition – no longer abstract. (This is necessary for the planned language extension mechanism. However, there is no concrete syntax yet for a Definition that is not of some more specialized type.)
3. Usage – no longer abstract. (This is necessary for the planned language extension mechanism. However, there is no concrete syntax yet for a Usage that is not of some more specialized type.)

_Validation:_

1. A MetadataFeature (formerly AnnotatingFeature) is equired to have a concrete Metaclass as its type. A MetadataUsage (subclass of MetadataFeature) is required to have a concrete MetadataDefinition (subclass of Metaclass) as its type.
2. If a MetadataFeature (or MetadataUsage) (concretely) subsets/redefines the `Metaobjects::annotatedElement` feature, then each of the `annotatedElements` of the MetadataFeature must conform to the types of one of the subsetting/redefining features.
3. Each owned Feature of a MetadataFeature (or MetadataUsage) must pass the following validation checks:
    - It must redefine a Feature (owned or inherited) of a supertype of its owning Feature.
    - If it has a FeatureValue, the `value` Expression must be model-level-evaluable.
    - Each of its owned Features (if any) must also pass these validation checks.

**Concrete Syntax**

1. An AnnotatingElement declared as a Namespace `ownedMember`, without any explicit Annotation relationships (i.e., having no **_about_** clause, except for the `/** ... */` notation, as discussed below), is no longer parsed with an implicit Annotation relationship to its `owningNamespace`. Such an AnnotatingElement is considered to annotate its `owner` Element without the need for such a relationship (see the update to `AnnotatingElement::annotatedElement` described above). An AnnotatingElement that is not owned by a Namespace is parsed as being the `ownedRelatedElement` of an Annotation relationship with the `owningRelatedElement` being the `annotatedElement` (currently, this is only possible if the AnnotatingElement is used in with the **`element`** and **`relationship`** notation in KerML).
2. A documentation Comment starting with the **`doc`** keyword is now parsed as a Documentation Element and always annotates its `owner`. Therefore, if the Documentation is of a Namespace (the usual case), it will not have any Annotation relationship.
4. A Comment using the form `/** ... */` is now parsed as a regular Comment that is an `ownedMember` of a containing Namespace, _not_ as Documentation. Therefore, the keyword **`comment`** is now used with such a Comment, rather than **`doc`**. The Comment is given an implicit Annotation relationship to the lexically next element in the containing Namespace body. Note that this means that, in a sequence of such Comments, each Comment in the sequence except the last is parsed as annotating the following comment. (Previously, the specification stated that this notation was for a documentation Comment on the lexically next Element, which means it would have had to be owned by that Element. However, the implementation actually parsed the notation as a Comment annotating the Membership owning the lexically next Element, with a sequence of such Comments all annotating the same Membership.)
5. A declaration using the **`metadata`** keyword or `@` symbol is parsed as a MetadataFeature in KerML and as a MetadataUsage in SysML.
7. Most syntactic restrictions on the `ownedFeatures` of a MetadataFeature (`ownedUsages` of a MetadataUsage) have been removed, except that they must begin with a redefinition and cannot declare a different name than their effective names. (However, such Features must pass the validation checks described above.)
8. The `nestedUsages` of a MetadataUsage are parsed as ReferenceUsages. The optional keyword for their declaration is now **`ref`** (instead of **`feature`**), as usual for a ReferenceUsage.
9. A Metaclass is a Structure that is declared using the keyword **`metaclass`**.
10. A MetadataDefinition is an ItemDefinition (and a Metaclass) that is declared using the keyword **`metadata def`**.

**Kernel Library**

1. _`Metaobjects`_ – new package with the following members:
    - Metaclass _`Metaobject`_ (subclassifies Objects::Object) – the implicit base type of all Metaclasses.
    - Metaclass _`SemanticMetadata`_ – this will be used in the language extension mechanism to be implemented in ST6RI-521.
    - Feature _`metaobjects`_ – the implicit base type of all MetadataFeatures. (This is not itself a MetadataFeatures, because MetadataFeatures are always annotations, while _`metaobjects`_ is not.)
2. _`KerML`_ – changed all **`struct`** declarations to **`metaclass`** (with _`Element`_ implicitly subclassifying _`Metaobject`_). (Note that the reflective _`KerML`_ abstract syntax model is to be completed in ST6RI-417, which will likely be deferred again to the 2022-04 sprint.)

**Systems Library**

1. _`Metadata`_ – new package with the following members:
   - Metadata definition _`MetadataItem`_ (subclassifies _`Items::Item`_ and _`Metaobjects::Metaobject`_) – the implicit base type of all MetadataDefinitions.
   - Item usage _`metadataItems`_ – the implicit base type of all MetadataUsages. (This is not itself a MetadataUsage, because MetadataUsages are always annotations, while _`metadataItems`_ is not.)
2. _`SysML`_ – changed all **`item def`** declarations to **`metadata def`**. (Note that the reflective _`SysML`_ abstract syntax model is to be completed in ST6RI-417, which will likely be deferred again to the 2022-04 sprint.)

**Domain Libraries**

1. Changed attribute definitions, when intended to be used to define metadata, to metadata definitions, in packages `AnalysisTooling`, `ModelingMetadata` and `RiskMetadata`.

### CODE REVIEW

**Comment by seidewitz** [comment]
@manasbajaj @ivan-gomes 

The `SysML.uml` file on this branch should be ready for use in generating an API update.

@himi

I have minimally updated the PlantUML code, but I have not tested the changes or made any substantive updates for the revisions in the annotation abstract syntax. Revisions to handle this can be done as part of ST6RI-529. Please merge the ST6RI-520 branch into ST6RI-529 (_not_ the other way around!) and let me know if there are any issues.

**Comment by seidewitz** [comment]
@manasbajaj @ivan-gomes 

The `SysML.uml` file on this branch should be ready for use in generating an API update.

@himi

I have minimally updated the PlantUML code, but I have not tested the changes or made any substantive updates for the revisions in the annotation abstract syntax. Revisions to handle this can be done as part of ST6RI-529. Please merge the ST6RI-520 branch into ST6RI-529 (_not_ the other way around!) and let me know if there are any issues.

**Comment by himi** [comment]
@seidewitz I see. I will not touch this branch and merge it to ST6RI-529.

**Comment by ivan-gomes** [comment]
Not a blocker for API generation, but just something I stumbled upon while reviewing, there are references to `AnnotatingFeature` in `SysML.uml` at `L1632`, `L1687`, and `L2249`.

**Review by ivan-gomes — APPROVED** [review]
Corresponding API update @ https://github.com/Systems-Modeling/SysML-v2-API-Services/pull/67

**Review by himi — APPROVED** [review]
While the visualizer does not properly work with the changes, I confirmed other metadata features worked.  I'll work on the visualizer in ST6RI-529.

**Comment by seidewitz** [comment]
> Not a blocker for API generation, but just something I stumbled upon while reviewing: there are references to the now removed `AnnotatingFeature` in `SysML.uml` at `L1632`, `L1687`, and `L2249`.

Thanks for catching these. They are in documentation and OCL that isn't used in the implementation. But we can fix them in the metamodel before generating the spec docs for the 2022-03 release.

**Pull request merged**
