### PR TITLE
ST6RI-361 Update implementation for 2021-04 metamodel baseline

### PR DESCRIPTION
**Pull request by seidewitz**
This pull request updates the EMF metamodel implementation to the 2021-04 baseline. Important changes in the 2021-04 baseline include the following:

1. _Effective name._ In certain cases, Elements for which the modeler has given no name are given an _effective name_ that can be used just like an explicitly modeled name. For example, a redefining Feature with no modeler-given name takes the name of its redefined Feature as its effective name. The formerly implementation-specific mechanism for effective names is now part of the metamodel baseline. In particular, the methods `Element::getEffectiveName` and `Membership::getEffectiveMemberName` (which replaces `MembershipImpl::getMemberEffectiveName`) now appear on the public EMF API.

   *Note:* The update also adds a method to the Element interface for the `effectiveName` operation from the metamodel. This means that, in Xtend, one cannot use the shorthand `e.effectiveName` to call the `getEffectiveName` method on Element `e`, because this conflicts with the name of the `effectiveName` method. Instead, one needs to use `e.getEffectiveName`.

2. _Imported and inherited memberships._ A parameter has been added to the Namespace operations `importedMemberships` and `publicMemberships` to pass in a set of Namespaces to be `excluded` during model traversal. This is to allow the handling of cyclic imports in the formal specification of these operations. The operations are implemented as calling existing implementation methods in NamespaceImpl, which already had such a parameter. The operation `inheritedMembers` has also been added to the Type, with a similar `excluded` parameter, implemented by calling an existing method in TypeImpl.

3. _Stakeholder and concern abstract syntax._ The metamodel baseline has new abstract syntax for StakeholderDefinitions/Usages (as kinds of PartDefinitions/Usages) and ConcernDefinitions/Usages (as kinds of RequirementDefinitions/Usages). The abstract syntax has also been updated to allow RequirementDefinitions and RequirementUsages to address concerns (viewpoints are also kinds of requirements) and for a derived property of ViewpointDefinitions and ViewpointUsages that identifies the stakeholders whose concerns are addressed by a viewpoint.

   *Note:* The changes in this pull request do _not_ include any new concrete syntax or library models for stakeholders and concerns. Those will be added during the implementation of [ST6RI-362 Stakeholders, concerns and renderings](https://openmbee.atlassian.net/browse/ST6RI-362).

4. _Query path expressions._ The metaclass PathStepExpression replaces QueryPathStepExpression, and PathSelectExpression replaces QueryQualifierExpression. The functionality of the classes is unchanged. The metaclass QueryPathExpression has been removed, because FeatureReferenceExpression can be used directly instead.

   *Note:* This pull request does _not_ change the existing concrete syntax for query path expressions. It simply parses that surface syntax to the new classes. Replacing the QPE syntax will be addressed in [ST6RI-196 Feature reference "dot" expressions](https://openmbee.atlassian.net/browse/ST6RI-196).

5. _"Packaged" visibility._ The VisibilityKind `package` (indicated in the concrete syntax by the keyword *`packaged`*) has been removed.

@manasbajaj @ivan-gomes 
The `SysML.uml` abstract syntax metamodel file on this branch is now ready for use in generating an API release candidate for 2021-04.

Added metaclasses:
- AddressedConcernMembership
- ConcernDefinition
- ConcernUsage
- PathSelectExpression
- PathStepExpression
- StakeholderDefinition
- StakeholderUsage
- ViewRenderingMembership

Removed metaclasses:
- BlockExpression
- InstanceCreationExpression
- QueryPathExpression
- QueryPathStepExpression
- QueryQualifierExpression

### CODE REVIEW

**Comment by himi** [comment]
I tried this version and got the following error when visualizing 8-Requirements.sysml.  I think it is because SatisfyRequirementUsageImpl.basicGetSatisfyingFeature() does not check the size of the slot.

org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=1, size=1
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)
	at org.omg.sysml.lang.sysml.impl.SatisfyRequirementUsageImpl.basicGetSatisfyingFeature(SatisfyRequirementUsageImpl.java:167)
	at org.omg.sysml.lang.sysml.impl.SatisfyRequirementUsageImpl.getSatisfyingFeature(SatisfyRequirementUsageImpl.java:156)
	at org.omg.sysml.plantuml.VStructure.caseSatisfyRequirementUsage(VStructure.java:232)
	at org.omg.sysml.plantuml.VStructure.caseSatisfyRequirementUsage(VStructure.java:1)
	at org.omg.sysml.lang.sysml.util.SysMLSwitch.doSwitch(SysMLSwitch.java:1797)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.omg.sysml.plantuml.Visitor.visit(Visitor.java:400)
	at org.omg.sysml.plantuml.VTraverser.visitMembership(VTraverser.java:77)
	at org.omg.sysml.plantuml.VTraverser.caseMembership(VTraverser.java:82)
	at org.omg.sysml.plantuml.VTraverser.caseMembership(VTraverser.java:1)
	at org.omg.sysml.lang.sysml.util.SysMLSwitch.doSwitch(SysMLSwitch.java:238)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.omg.sysml.plantuml.Visitor.visit(Visitor.java:400)
	at org.omg.sysml.plantuml.VTraverser.traverse(VTraverser.java:67)
	at org.omg.sysml.plantuml.VComposite.caseUsage(VComposite.java:74)
	at org.omg.sysml.plantuml.VComposite.caseUsage(VComposite.java:1)
	at org.omg.sysml.lang.sysml.util.SysMLSwitch.doSwitch(SysMLSwitch.java:1209)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.omg.sysml.plantuml.Visitor.visit(Visitor.java:400)
	at org.omg.sysml.plantuml.VTraverser.visitMembership(VTraverser.java:77)
	at org.omg.sysml.plantuml.VTraverser.caseMembership(VTraverser.java:82)
	at org.omg.sysml.plantuml.VTraverser.caseMembership(VTraverser.java:1)
	at org.omg.sysml.lang.sysml.util.SysMLSwitch.doSwitch(SysMLSwitch.java:96)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.omg.sysml.plantuml.Visitor.visit(Visitor.java:400)
	at org.omg.sysml.plantuml.VTraverser.traverse(VTraverser.java:67)
	at org.omg.sysml.plantuml.VTraverser.caseNamespace(VTraverser.java:90)
	at org.omg.sysml.plantuml.VStructure.caseNamespace(VStructure.java:221)
	at org.omg.sysml.plantuml.VTree.caseNamespace(VTree.java:216)
	at org.omg.sysml.plantuml.VTraverser.caseNamespace(VTraverser.java:1)
	at org.omg.sysml.lang.sysml.util.SysMLSwitch.doSwitch(SysMLSwitch.java:638)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.omg.sysml.plantuml.Visitor.visit(Visitor.java:400)
	at org.omg.sysml.plantuml.SysML2PlantUMLText.sysML2PUML(SysML2PlantUMLText.java:348)
	at org.omg.sysml.plantuml.eclipse.SysMLDiagramTextProvider.getDiagramText(SysMLDiagramTextProvider.java:131)
	at net.sourceforge.plantuml.text.AbstractDiagramTextProvider.getDiagramText(AbstractDiagramTextProvider.java:55)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView.getDiagramText(AbstractDiagramSourceView.java:576)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView.updateDiagramText(AbstractDiagramSourceView.java:597)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView.updateDiagramText(AbstractDiagramSourceView.java:551)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView$DiagramTextChangedListener.diagramChanged(AbstractDiagramSourceView.java:390)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView$DiagramTextChangedListener.selectionChanged(AbstractDiagramSourceView.java:385)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:266)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.handlePostSelectionChanged(SelectionService.java:123)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.lambda$2(SelectionService.java:78)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$3.run(SelectionAggregator.java:163)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.notifyPostListeners(SelectionAggregator.java:160)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.access$7(SelectionAggregator.java:158)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6.lambda$0(SelectionAggregator.java:250)
	at org.eclipse.e4.core.contexts.RunAndTrack.runExternalCode(RunAndTrack.java:59)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6.changed(SelectionAggregator.java:250)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:108)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:364)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:379)
	at org.eclipse.e4.ui.internal.workbench.SelectionServiceImpl.setPostSelection(SelectionServiceImpl.java:39)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.lambda$2(CompatibilityPart.java:128)
	at org.eclipse.jface.text.TextViewer.firePostSelectionChanged(TextViewer.java:2638)
	at org.eclipse.jface.text.TextViewer.firePostSelectionChanged(TextViewer.java:2585)
	at org.eclipse.jface.text.TextViewer$2.run(TextViewer.java:2564)
	at org.eclipse.swt.widgets.Display.runTimer(Display.java:4128)
	at org.eclipse.swt.widgets.Display.messageProc(Display.java:3252)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3628)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)

**Comment by himi** [comment]
I did not change anything.  Just I launched Eclipse and opened 8-Requirements.sysml and I got "Problem Occurred" window notifying the exception attached.

**Comment by seidewitz** [comment]
Interesting. I did the same and didn't get any error. Did you do a clean re-build of sysml.library before opening 8-Rquirements.sysml? Did you already have the PlantUML view active when you opened the file?

**Comment by himi** [comment]
You're right.  I cleaned sysml.library again and the error disappeared.  I thought first I cleaned the workspace but something wrong might happened after that.   I'll keep in mind to cleanup before reporting.

**Comment by himi** [comment]
@seidewitz I see.  Maybe, that's the reason.  I had cleaned the entire workspace, and it might cause the problem.  Thank you.

**Review by himi — APPROVED** [review]

**Comment by himi** [comment]
I also tested it in a brand new environment (2021-06/MacOS arm (M1) environment) and it worked fine.  QPE migrations also worked. But as you said, we need to work on the new syntax, ST6RI-196 for that.

**Review by ivan-gomes — APPROVED** [review]
lgtm

**Pull request merged**
