### PR TITLE
ST6RI-299: Properly show exhibit state usages in PlantUML visualization

### PR DESCRIPTION
**Pull request by himi**
See https://openmbee.atlassian.net/browse/ST6RI-299 for details. 
**Notice that you need to update PlantUML to version 1.2020.14.himi4**

### CODE REVIEW

**Comment by seidewitz** [comment]
Is there any change needed to the Oomph installer configuration for the new PlantUML version, or will it pick up the latest version automatically?

**Comment by seidewitz** [comment]
When I try to update PlantUML from https://dl.bintray.com/himi-sysml/plantuml-sysmlv2/updates/, it doesn't see any new versions.

**Comment by himi** [comment]
Did you find the version of https://dl.bintray.com/himi-sysml/plantuml-sysmlv2/releases/1.1.25.202011301838/?
My `mvn package` said:

`[INFO] Fetching p2.index from https://dl.bintray.com/himi-sysml/plantuml-sysmlv2/updates/1.1/ (146B)
[INFO] Fetching p2.index from https://dl.bintray.com/himi-sysml/plantuml-sysmlv2/releases/1.1.25.202004090529/ (176B)
...snip...
[INFO] Fetching p2.index from https://dl.bintray.com/himi-sysml/plantuml-sysmlv2/releases/1.1.25.202011301838/ (172B)
`

Regarding your question, yes, it should pick up the latest version automatically.

**Comment by himi** [comment]
Just FYI, for ST6RI-299, I need to update PlantUML again.

**Comment by seidewitz** [comment]
> Did you find the version of https://dl.bintray.com/himi-sysml/plantuml-sysmlv2/releases/1.1.25.202011301838/?
> My `mvn package` said:
> 
> `[INFO] Fetching p2.index from https://dl.bintray.com/himi-sysml/plantuml-sysmlv2/updates/1.1/ (146B) [INFO] Fetching p2.index from https://dl.bintray.com/himi-sysml/plantuml-sysmlv2/releases/1.1.25.202004090529/ (176B) ...snip... [INFO] Fetching p2.index from https://dl.bintray.com/himi-sysml/plantuml-sysmlv2/releases/1.1.25.202011301838/ (172B) `

Yes, I also got this in the Maven build, which I am running in Eclipse. However, the build then failed on the jupyter-system-kernel step because it couldn't find `VizResult`:

```
Viz.java:47: error: cannot access VizResult
     VizResult vr = ISysML.getKernelInstance().getInteractive().viz(elements, views, styles);`   
      ^ class file for VizResult not found
```

In Eclipse, there is also an error in the `MANIFEST.MF` file for org.omg.sysml.plantuml, because I don't have the latest version of net.sourceforge.plantuml installed. And, when I try to install the latest version into Eclipse, it doesn't find any new versions on the update site.

**Comment by himi** [comment]
It looks strange.  VizResult is provided by org.omg.sysml.interactive package, not PlantUML.  Yes, I updated MANIFEST.MF to depend it on net.sourceforge.plantuml;version="1.2020.14.himi4", corresponding to 1.1.25.202011301838.  So I think org.omg.sysml.interactive build had been failed.  Could you please send your maven build log to check it?

In Eclipse environment, you need to update PlantUML in your environment with Help->Install New Software.

**Comment by seidewitz** [comment]
> In Eclipse environment, you need to update PlantUML in your environment with Help->Install New Software.

I know that. As I said originally

> When I try to update PlantUML from https://dl.bintray.com/himi-sysml/plantuml-sysmlv2/updates/, it doesn't see any new versions.

By "update" I meant "with Help->Install New Software".

**Comment by himi** [comment]
This is the Install dialog in my environment, and how does it look like in your environment?

**Comment by seidewitz** [comment]
As suggested by @ujhelyiz, I restarted Eclipse. After that, I saw the new versions on the update site, the same as the screenshot you provided. After installing the latest versions from the site, I was able to successfully rebuild.

**Review by seidewitz — CHANGES_REQUESTED** [review]
If you are going to label an ExhibitStateUsage as `«exhibit state»`, then, for consistency, a PerformActionUsage should be labeled as `«perform action»`, not `«performAction»`.

**Comment by himi** [comment]
@Ed, thank you.  I'll fix it.  How about AcceptActionUsage? Should it be <<accept action>>?

**Comment by seidewitz** [comment]
> @ed, thank you. I'll fix it. How about AcceptActionUsage? Should it be `<<accept action>>`?

Well, if you can do it easily, it would be nice to label AcceptActionUsage as `«accept action»` and SendActionUsage as `«send action»`. That's probably enough, then, for this task!

**Comment by himi** [comment]
Thank you.  I fixed to show SendActionUsage as well.

**Comment by seidewitz** [comment]
It to work in the Tree view, but not the Interconnection view. For example, from 5-State-based Behavior-1:

image

**Comment by himi** [comment]
Thank you.  I fixed the bug.  It's wrongly configured in the Interconnection view specific style.

**Comment by seidewitz** [comment]
Looks good now!

**Review by seidewitz — APPROVED** [review]

**Pull request merged**
