### PR TITLE
ST6RI-615 Update supported Eclipse version to 2022-09

### PR DESCRIPTION
**Pull request by seidewitz**
This pull request updates the development environment for the SysML v2 Pilot Implementation to Eclipse version 2022-09. It includes the following changes.

1. `org.omg.sysml.installer/SysML.setup`
   * Updated Eclipse download URL to 2022-09
   * Updated Xpect URL from `lastBuild` to `lastSuccessfulBuild`
   * Removed `org.omg.xtend` (this was not resolving on installation and no longer seems to be necessary)

2. `org.omg.kerml.expressions.xtext`, `org.omg.kerml.xtext` and `org.omg.sysml.xtext`
   * Regenerated parsers
   * Updated `org.objectweb.asm` dependency version to 9.3.0

3. `org.omg.kerml.xpect.tests`
   * Updated project Java version to 11
   * Added dependency on `org.aopalliance` plugin (needed to avoid class not found exception)

4. `org.omg.sysml.xpect.tests`
   * Updated project Java version to 11

5. `org.omg.sysml`
   * Updated `Launch Runtime Eclipse` execution environment to OSGi/Minimum-1.2.

6. `org.omg.sysml.uml.ecore.importer`
   * Updated compiler compliance level to Java-17 (necessary to install the plugin into the Eclipse environment)

7. `SysML-v2-PilotImplementation/pom.xml`
   * Updated `tycho-version` to 2.7.5
   * Updated `eclipse-repository` to 2022-09
   * Updated `xtext.version` to 2.28.0
   * Updated `junit.version` (really Surefire version) to 3.0.0-M7
   * Updated `asciidoctor.maven.plugin.version` to 2.2.0
   * Replaced `tycho-source-feature-plugin:source-feature` with `tycho-source-plugin:feature-source`

### CODE REVIEW

**Review by ivan-gomes — APPROVED** [review]
No anticipated impact on Jupyter integration.

**Review by himi — APPROVED** [review]
I tested it with MacOS 13.0.1, Windows 11 and Linux  environment, on Adoptium OpenJDK11, and found no problem.  I could run Eclipse environment with OpenJDK 11.  
It might be better just specifying OSGi/Minimum-1.2 for Eclipse to choose its JRE.

Screenshot 2022-11-17 at 1 46 13 PM

**Comment by seidewitz** [comment]
> It might be better just specifying OSGi/Minimum-1.2 for Eclipse to choose its JRE.

I have Java 11 set as the default JRE in my Eclipse preferences, so, if I specify OSGi/Minimum-1.2, it selects Java 11, and the runtime instance doesn't run.

**Comment by himi** [comment]
Oh, I see.  I have no idea why it did not run with OpenJDK11 in your environment.  Maybe it is because I installed the latest version from https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.17%2B8

**Comment by seidewitz** [comment]
Ah, I think the problem was that I was selecting a Java 11 JRE that was still for the x64 architecture. Once I installed the 11.0.17 JDK for the aarch64 architecture, I could launch the runtime instance without any problem using that.

**Pull request merged**
