### PR TITLE
ST6RI-486: Render RequirementConstraintMemberships in compartments

### PR DESCRIPTION
**Pull request by himi**
Render RequirementConstraintMemberships in compartments when COMPMOST is enabled or the constraint is anonymous

### CODE REVIEW

**Review by seidewitz — CHANGES_REQUESTED** [review]
The code

```
requirement <'2.1'> vehicleMass2: MassLimitationRequirement {
	doc /* The vehicle mass shall be less than or equal to 2500 kg when the fuel tank is empty. */
	subject vehicle : Vehicle;	
	attribute :>> massActual: MassValue = vehicle.mass;
	attribute :>> massReqd = 2500 [kg];
	assume constraint fuelConstraint {
		doc /* empty fuel tank */
		vehicle.fuelLevel == 0.0
	}
}
```
is visualized as follows:
image

The rendering of the assumed constraint has a few problems:

1. The `assumes` keyword is italic rather than bold (`requires` is correctly bold).
2. There is a spurious nested `constraint fuelConstraint` construct.
3. The line breaks between nested body elements are lost, making the text difficult to read.

**Comment by himi** [comment]
Regarding 3, I made it unfold texts but still it contains intends.   Could you please check the results to see if it fits with your request?

**Comment by seidewitz** [comment]
Your resolutions to points 1 and 3 are OK. But there are still problems with 2.

image

The line **`assume`**`fuelConstraint constraint fuelConstraint` should be just `**`assume`**`fuelConstraint`. Similarly, an unnamed required constraint appears as **`require`**`constraint`, when it should just be **`require`** (as it is already in a "constraints" compartment).

**Comment by himi** [comment]
The corrensponding text of ConstraintUsage constains `constarint` keyword and it's tricky to exclude that.  I tried to construct text programatically but it requires a lot of cases including documentation.   So I decided to just exclude the keyword.

**Pull request merged**
