### PR TITLE
ST6RI-437: Render unnamed actions and states, and remove inappropriate satisfying feature links. (PlantUML)

### PR DESCRIPTION
**Pull request by himi**
This PR fixes the visualization problems of:

- Unnamed actions and states are not rendered;
- Wrong `<<satisfy>>` links may appear when SatisfyRequirementUsage is incomplete;
- PlantUML error in sequence view reported in ST6RI-436.

### CODE REVIEW

**Comment by himi** [comment]
In the review, it is pointed out that messages should be rendered as open arrows because they are defined as asynchronous ones.  So I fixed it in 6bfdcd3.

**Comment by seidewitz** [comment]
In all the examples I have tried so far, none of the SatisfyRequirementUsages are being visualized at all. Has the "satisfy" visualization been removed, or are there specific cases in which it is still shown?

**Comment by himi** [comment]
@seidewitz the situation I encountered is not a normal situation.  We have many SatisfyRequirementUsage for example, in 8-Requirements validation case.  Normally, such SatisfyRequirementUsage has satisfiedRequirement and satisfyingFeature.  However, typically during the incomplete build, these cannot be resolved and these might return null.  In this situation, wrong <<satisfy>> links had been rendered.  This fix prevents such wrong link rendering.

**Comment by seidewitz** [comment]
The 8-Requirements validation case model includes the following:
```
	part 'vehicle1_c2 Specification Context' {
		import 'vehicle1-c2 Specification'::*;
		
		requirement 'vehicle1-c2 Specification' {
			subject vehicle : Vehicle;
			require vehicleMass2;
			require vehicleReliability2;
		}
		
		satisfy 'vehicle1-c2 Specification' by vehicle1_c2;
	}
```
The satisfy in this model used to be rendered incorrectly (as a dashed arrow pointing to a final node symbol). Now it is not rendered at all:
image
This about as normal a satisfy as there is. Nothing is incomplete.

**Comment by himi** [comment]
I confirmed it in 8-Requirements validation case... By attaching a debugger, I found satisfyingFeature was null... I'm investigating the reason.

**Comment by seidewitz** [comment]
You are right, `basicGetSatisfyingFeature` was implemented incorrectly. I created a separate issue for this, in order to track it as a bug (see [ST6RI-444](https://openmbee.atlassian.net/browse/ST6RI-444)). I have also made the fix and create PR #275 for it. 

When this fix is merged into the ST6RI-390 branch, the satisfy arrows are then rendered between the correct elements. However, the arrow is going in the wrong direction.

**Review by seidewitz — CHANGES_REQUESTED** [review]
The `<<satisfy>>` arrows are being rendered in the wrong direction. They should go _from_ the satisfying feature _to_ the satisfied requirement.

**Comment by himi** [comment]
@seidewitz Thank you.  I corrected the direction.

**Comment by himi** [comment]
BTW, Sandy requested to add some example in the help string.  I'll add it.

**Review by seidewitz — APPROVED** [review]

**Pull request merged**
