### PR TITLE
ST6RI-711 Example models from KerML Spec Annex A

### PR DESCRIPTION
**Pull request by conradbock**
This pull request adds, under `kerml/examples/KerML Annex A Examples`, models used as examples in Annex A: Model Execution of the KerML Specification:

- `A-2-Atoms.kerml`
- `A-2-ModelingInstances.kerml`
- `A-3-2-WithoutConnectors.kerml`
- `A-3-3-OneToOneConnectors.kerml`
- `A-3-4-OneToUnrestrictedConnectors.kerml`
- `A-3-5-TimingForStructures.kerml`
- `A-3-6-Sequences.kerml`
- `A-3-7-DecisionsAndMerges.kerml`
- `A-3-8-ChangingFeatureValues.kerml`

It is expected that these models will be included as informative artifacts with the finalized 1.0 specification.

### CODE REVIEW

**Comment by seidewitz** [comment]
Note: The following corrections were made in commit [ec24fa1](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/503/commits/ec24fa1ffa1867604887ad951880e8922dde02b9):

A-3-3-OneToOneConnectors.kerml: in MyBikeWheel-Fork-BWF-Link, hypens => underscores 

A-3-4-OneToUnrestrictedConnectors.kerml:

* MyBasket2_BikeFork1_BBF_Link => MyBikeBasket2_Fork1_BBF_Link

* MyBikeFork1_Basket1_BBF_Link => MyBikeBasket1_Fork1_BBF_Link

* MyBikeFork1_Basket2_BBF_Link => MyBikeBasket2_Fork1_BBF_Link

A-3-5-TimingForStructures.kerml: MyBike_While_Fork2End_Link => MyBikeEnd_While_Fork2End_Link

A-3-6-Sequences.kerml: third to last line (step redefines dry : MyShip [1]), dry => ship.

A-3-8-ChangingFeatureValues.kerml:

* Insert "redefines" as a separate word between the two "feature startShot".

* Move "dry.dried.endShot" to just before the following semi-colon and precede it by "chains ".

**Comment by bjorncole** [comment]
The models appear to have the right contents to go with our examples.

**Comment by seidewitz** [comment]
@bjorncole 
Please submit an official review approving the PR. Thanks.

**Review by bjorncole — APPROVED** [review]
Model contents match expectations. Approved.

**Pull request merged**
