### PR TITLE
ST6RI-317: Automate Maven Build with Travis-CI

### PR DESCRIPTION
**Pull request by himi**
It also tests pull request integration.

### CODE REVIEW

**Comment by seidewitz** [comment]
As far as I can tell, the automation works. However, it seems that the "several weeks" for the transition of travis-ci.org to travis-ci.com are just about over, and the transition will be complete on December 31 (see [https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom)). This does not appear to have been very well announced.

Since the transition is happening before the end of the 2020-12 sprint, we need to migrate our repositories to travis-ci.com before closing this issue.

**Comment by himi** [comment]
I've just migrated plantuml repository to travis-ci.com.  It seems we, more specifically, you, need to take an action for it because I do not have admin privilege.  Please sign up travis-ci.com and migrate SysML-v2-Pilot-Implementation repository in Settings.  Unlike travis-ci.org, GitHub apps manages the integration with travis-ci.com and in GitHub console, you can choose which repositories should be managed in travis-ci.com.  No other changes including .travis.yml do not seem to be needed.

**Review by seidewitz — APPROVED** [review]
Migration to travis-ci.com is complete. Please confirm that you can access the account.

**Comment by himi** [comment]
Yes, I could access it.

**Pull request merged**
