### PR TITLE
ST6RI-745 Inherited references are not properly rendered (PlantUML)

### PR DESCRIPTION
**Pull request by himi**
Mainly due to my mistakes, some inherited references were not correctly rendered with `SHOWINHERITED` style and this PR fixes those issues. 

Notice that ST6RI-745 branches out from ST6RI-744.  So it contains the fixes in ST6RI-744 as well.

### CODE REVIEW

**Comment by himi** [comment]
After this fix:
```
part p1 {
	part p11;
	part p12 :> p11;
}
part p2 :> p1;
```
is correctly rendered with `SHOWINHERITED` in Interconnection view as:

**Comment by himi** [comment]
Also the example below:
```
action a1 {
       	action a11 {
            out output;
        }
        flow f1 from a11.output to a12.input;
       	action a12 {
      	     in input;
       	}
}
action a2 :> a1;
 action a3 :> a1 {
        action :>> a11;
}
```

is correctly rendered as:

Screenshot 2024-02-23 at 11 35 47 AM

**Comment by himi** [comment]
Opps... This still has an issue.  `a3.a11` must redefine `a1.a11` instead of `a2.a11`.  I will fix it.

**Comment by himi** [comment]
I could fix that issue as well:
Screenshot 2024-02-23 at 12 30 41 PM

**Review by seidewitz — APPROVED** [review]

**Pull request merged**
