### PR TITLE
ST6RI-571: Visualization of feature values as bindings (PlantUML)

### PR DESCRIPTION
**Pull request by himi**
Visualize feature values as bindings.

### CODE REVIEW

**Comment by himi** [comment]
```
package ParameterBindingTest {
    action action0 {
        action action1{
            out out1;
            action action1_1{
                in in1 = action1.out1;
            }
        }
    }
 
    part p1 {
        in in1;
        part p2 {
            out out1 = in1;
        }
    }
}
```

is visualized as
test

**Comment by himi** [comment]
Added a new test:
```
package ParameterBindingTest {
     action action0{
          action action1{
              in in1;
              action action1_1{
                  in in1_1 = action1.in1;
              }
          }
      }
}
```, which gives:
![test2](https://user-images.githubusercontent.com/10537/181512256-9183212a-d299-4a0c-9d68-dd410ff80f9d.png)

**Comment by seidewitz** [comment]
In the following model:
```
package P {
    action a {
        in x;
    }
}
```
clicking on the line `in x;` when visualizing an Interconnection diagram in the Eclipse error results in the following PlantUML error message:
image

This also happens on master, but I only noticed it when checking out this branch. If you can reproduce it, is there an obvious fix you would like to include with this PR, or should I create a new bug report?

**Comment by himi** [comment]
It happens only in Interconnection view.  I made a simple fix for it.

**Review by seidewitz — APPROVED** [review]
Looks good.

**Pull request merged**
