### PR TITLE
ST6RI-411: Dot-notation expression visualization (PlantUML)

### PR DESCRIPTION
**Pull request by himi**
Visualize connectors with dot-notation expressions.
This PR includes a bug fix of interconnection view.

### CODE REVIEW

**Review by seidewitz — CHANGES_REQUESTED** [review]
Consider the following model:
```
package ConnectionTest {
	part p {
		part x {
			part x1;
		}
	}
	part def P {
		part y;		
		connect p to y;		
		part p1 :> p;
		connect p1.x to y;		
		connect p1.x.x1 to y;
	}
}
```
The interconnection visualization is:
image
This has the following problems:
1. The second and third connections are shown as being on nest features of `p`, not `p1`.
2. The third connection is shown as connecting to `x` rather than `x1`.

**Comment by himi** [comment]
I have not yet addressed the inherited case but first fix the case of `p1.x.x1`

**Comment by seidewitz** [comment]
I can confirm that the test model I gave earlier does now visualize with `y` connected to `x1`.

If you are going to address the visualization of connections to inherited elements in this PR, please have the update pushed no later than then end of Monday afternoon (28 July). Otherwise, you can include it in ST6RI-412 for 2021-06.

**Comment by himi** [comment]
Done.  It should work with inherited features.

**Review by seidewitz — APPROVED** [review]
Looks good!

**Pull request merged**
