### PR TITLE
ST6RI-622 Update the KerML and SysML metamodel URIs per OMG guidelines

### PR DESCRIPTION
**Pull request by seidewitz**
The OMG uses a typical numeric version numbering system for its specifications (e.g., SysML 1.7, SysML 2.0, etc.). However, any machine-readable artifacts associated with a standard are versioned using a date-based version tag of the `yyyymmnn`. Each such artifact is given a URI that is a (`https`) URL that dereferences to the artifact itself on the OMG server. Since the SysML v2 final submission will be in February 2023, the version date will be `20230201`.

For EMF implementation reasons, the pilot implementation currently registers the combined SysML/KerML Ecore metamodel in Eclipse using the URI `http://www.omg.org/spec/SysML/2.0`. This PR changes the URI used in the implementation to be `https://www.omg.org/spec/SysML/20230201`, consistent with what will be used for the final submission. (It also similarly changes the URI to `https://www.omg.org/spec/KerML/20230201` in the `KerML_only.uml` file used for generation of the KerML JSON schema file.)

### CODE REVIEW

**Comment by seidewitz** [comment]
@ivan-gomes @himi 
Please review this as PR as soon as possible, or let me know if you will not be able to do it soon. Thanks.

**Comment by seidewitz** [comment]
@Weilkiti @YvesTLS 
Please note that this will change the URI that you need to use to identify the source metamodel in your transformation implementation.

**Review by himi — APPROVED** [review]
It's just metamodel URI or EPackage Namespace update and I found no problem.

**Review by ivan-gomes — COMMENTED** [review]
lgtm

**Pull request merged**
