### PR TITLE
ST6RI-734 Model-library-related Resolutions from KerML FTF Ballot #4

### PR DESCRIPTION
**Pull request by seidewitz**
This PR implements resolutions of issues from KerML FTF Ballot 4 that called for updates to library models.

*Note:* This PR is based off of branch ST6RI-736 (see PR #527).

Resolutions of the following issues are implemented in this PR:

[KERML-25](https://issues.omg.org/issues/KERML-25) Reflective KerML abstract syntax model has inconsistencies
[KERML-44](https://issues.omg.org/issues/KERML-44) Spatial links can be occurrences
[KERML-49](https://issues.omg.org/issues/KERML-49) Some readonly features are intended to have changing values
[KERML-158](https://issues.omg.org/issues/KERML-158) InsideOf association end feature redefines cross feature
[KERML-231](https://issues.omg.org/issues/KERML-231) LinkObject disjointness is redundant

Resolution of the following library-related issue did not require a library model update:

[KERML-39](https://issues.omg.org/browse/KERML-39) Link participant feature called an association end

### CODE REVIEW

**Comment by conradbock** [comment]
The resolution summary in [KERML-49](https://issues.omg.org/browse/KERML-49) says the `readonly` features identified in 4. Observation.kerml and 5. SpatialFrames.kerml are not to be removed, but the keyword seems to be missing from those features in branch ST6RI-724, and I couldn't find an FTF issue for removing them, was there one?

**Comment by seidewitz** [comment]
The **`readonly`** keywords on `Observation::defaultMonitor` and `SpatialFrames::defaultFrame` where removed as part of the resolution to KERML-56 (see PR #520, commit 62823d9).

**Comment by conradbock** [comment]
> The readonly keywords on Observation::defaultMonitor and SpatialFrames::defaultFrame where removed as part of the resolution to KERML-56

The revised text [KERML-49](https://issues.omg.org/browse/KERML-49) only changes the type of those features.  I don't remember discussing whether the defaults can change during an occurrence.  I suppose there's no harm since they're only defaults, but I can't find any FTF resolution about it.

**Comment by conradbock** [comment]
In any case, I can approve this pull.  Sorry I didn't notice the (seemingly) unballoted readonly changes in PR [#520](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/520).

**Review by conradbock — APPROVED** [review]

**Comment by seidewitz** [comment]
My point was that the removal of the readonly keywords you noted _was_ balloted, as the resolution to KERML-56, which was approved on KerML FTF Ballot 3. It was no longer necessary to have them be readonly, because the resolution to KERML-56 made them features of a true singleton type, so there is no way they could change value anyway. It was just neglected to note this in the later resolution to KERML-49.

**Comment by conradbock** [comment]
Makes complete sense, but where is the ballotted revised text that removes the `readonly` keyword?   Without that the standard libraries still have them.

**Comment by seidewitz** [comment]
Oops, you are right, the revised text of the resolution to KERML-56 as approved by the FTF on Ballot 3 _didn't_ actually removed the readonly keywords. While it doesn't really matter semantically in this case, I can put them back in to be consistent with the process.

**Pull request merged**
