### PR TITLE
ST6RI-302 Update implementation for 2020-12 metamodel baseline

### PR DESCRIPTION
**Pull request by seidewitz**
The 2020-12 baseline included the following major updates.

1. Renamed the Root metaclass `Package` to `Namespace` (along with associated property names).
2. Added an`isRecursive` property to `Import`. (ST6RI-311)
3. Added new abstract syntax for metadata annotations (`AnnotatingFeature` and associated classes) and metadata expressions (`MetadataExpression` and associated classes). (ST6RI-309, ST6RI-304)
4. Added a new Kernel metaclass called `Package` that is a subclass of `Namespace` (and a peer to `Type`), along with associated abstract syntax for `ElementFilter` (i.e., "smart packages). (ST6RI-303, ST6RI-305)
5. Added new Systems abstract syntax for `EnumerationDefinition` and `EnumerationUsage`. (ST6RI-306)

There are a number of additional Jira issues on the sprint to address the functional changes points 2 through 5, as indicated above. This pull request includes the following changes, responding to issue ST6RI-302:

1. Updates to the UML and Ecore metamodels for the new baseline, as well as the generated EMF code. While the renaming of `Package` to `Namespace` is not a functional change, it impacts code using the EMF API, including in the PlantUML projects. The intent is to make all necessary code changes to account for this, without any change in functionality.

2. Updates to the KerML and SysML grammars to allow a trailing `**` instead of `*` in an `import`, to indicate that the import `isRecursive`. But the `isRecursive` functionality is not implemented.

3. Renaming of the Systems model library packages `Analyses` and `Verifications` to `AnalysisCases` and `VerificationCases`. This is to avoid possible naming confusion when adding analysis-related domain models later in the sprint (ST6RI-310).

@ivan-gomes @manasbajaj The metamodel files should be ready for use in generating the 2020-12 API release.

### CODE REVIEW

**Review by ivan-gomes — CHANGES_REQUESTED** [review]
`InvocationExpression#argument` is ordered, ref: https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/88160c29384de0042fac4980d81c7cbf8b0458f0/org.omg.sysml/model/SysML.uml#L5284 but MetadataOperationExpression#argument` which redefines it is not, ref: https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/88160c29384de0042fac4980d81c7cbf8b0458f0/org.omg.sysml/model/SysML.uml#L5196 (implicitly because `isOrdered` is absent and defaults to false). I am assuming this is just a missing flag and `MetadataOperationExpression#argument` is intended to be ordered.

**Review by ujhelyiz — APPROVED** [review]
As far as I did understand, the changes seem reasonable to me; I did not check for possible conflicts with my changes in branch ST6RI-307.

**Comment by seidewitz** [comment]
@ivan-gomes 
Good catch. I have updated `SysML.uml` to correct this.

**Comment by seidewitz** [comment]
@ujhelyiz 
I neglected to describe one additional change on this branch in the pull request description. In commit 88160c2, I made a technical correction to a semantic problem with Connectors that I had introduced in the last sprint. This correction shouldn't have any user-visible effects, but it necessitated some other changes to work consistently, which might be more likely to conflict with your changes in ST6RI-307 than the substantive changes for ST6RI-302.

I am thinking of first merging the earlier commit 5ee3500 into ST6RI-307 and getting that to work, before then merging in the head of ST6RI-302.

**Review by himi — APPROVED** [review]
It works with the current SysMLv2-PlantUML visualization

**Review by ivan-gomes — APPROVED** [review]

**Comment by ivan-gomes** [comment]
> @ivan-gomes
> Good catch. I have updated `SysML.uml` to correct this.

Thanks! Confirmed it looks good.

**Pull request merged**
