### PR TITLE
ST6RI-403 Update implementation for 2021-06 metamodel baseline

### PR DESCRIPTION
**Pull request by seidewitz**
This PR implements the 2021-06 baseline metamodel, without updating the surface notation implementation for all new features (which will be done later). It also resolves ST6RI-375 (Importing a member using an alias does not work correctly) and ST6RI-392 (Directed features are not treated as parameters for requirements).

**Abstract Syntax Update**

_Metaclasses Added_

- ActorMembership
- AssignmentActionUsage
- BindingConnectorAsUsage
- ConnectorAsUsage _(abstract)_
- Disjoining
- FeatureChaining
- FlowConnectionUsage
- ForLoopActionUsage
- FramedConcernMembership _(renamed from AddressedConcernMembership)_
- IfActionUsage
- IncludeUseCaseUsage
- LiteralInfinity _(renamed from LiteralUnbounded)_
- LiteralRational _(renamed from LiteralReal)_
- LoopActionUsage _(abstract)_
- Specialization _(renamed from Generalization)_
- StakeholderMembership
- Subclassification _(renamed from Superclassing)_
- SuccessionAsUsage
- SuccessionFlowConnectionUsage
- UseCaseDefinition
- UseCaseUsage
- WhileLoopActionUsage

_Metaclasses Removed_

- AddressedConcernMembership _(renamed to FramedConcernMembership)_
- Generalization _(renamed to Specialization)_
- LiteralUnbounded _(renamed to LiteralInfinity)_
- LiteralReal _(renamed to LiteralRational)_
- StakeholderDefinition
- StakeholderUsage
- Superclassing _(renamed to Subclassification)_

**KerML Language Updates**

1. _Member Import._ Updated Import to handle single-membership imports. The notation **`import`**_`packageQualifiedName`_::`_`elementName`_`;` now sets the `importedNamespace` of the Import to the resolution of _`packageQualifiedName`_ and sets the `importedElementName` to _`elementName`_. The result is to import the Membership in the `importedNamespace` with the `memberName` given by the `importedElementName`, even if given name is an alias name. (This resolves ST6RI-375.)
2. _Import All._ Adding the **`all`** keyword to **`import`** now sets the `isImportAll` flag to true. Memberships are then imported without regard to visibility. Expose now always has `isImportAll = true`.
3. _Specialization._ Renamed Generalization to Specialization and Superclassing to Subclassification. These are just renamings of the metaclasses without any semantic or other syntactic difference (except that `Superclassing::subclass` has been renamed to `Subclassification::subclassifier` and `Superclassing::superclass` has been renamed to `Subclassification::superclassifier`).
4. _Feature Attributes._ Moved the meta-attributes `isComposite`, `isPortion`, `isDerived`, `isReadOnly` and `direction` from FeatureMembership to Feature. Also, `isEnd` is no longer derived.
5. _Parameters._ Updated the derivation of `parameter` for Behavior and Step to be all the `directedFeatures` (i.e., Features with a non-null direction). (This effectively also resolves ST6RI-392.) Updated Functions to have only **`in`** parameters, except for a single `result` **`out`** parameter).
6. _Feature Value Defaults._ Implemented the new `isDefault` flag on FeatureValue. If `isDefault = true`, then no BindingConnector is added when the FeatureValue is transformed.
7. _Literals._ Renamed LiteralReal to LiteralRational and LiteralUnbounded to LiteralInfinity. (Did _not_ rename LiteralInteger to LiteralNatural, in order to better accommodate literals as results of model-level evaluation. Setting the proper result types for LiteralExpressions is also still _not_ implemented.)

**SysML Language Updates**

1. _Ports._ Updated PortDefinition to subclass OccurrenceDefinition and PortUsage to subclass OccurrenceUsage.
2. _Perform Actions._ Updated PerformActionUsage to subclass EventOccurrenceUsage.
3. _Framed Concerns._ Renamed AddressedConcernMembership to FramedConcernMembership.
4. _Stakeholders._ Removed StakeholderDefinition and StakeholderUsage. Added stakeholderParameter to RequirementDefinition and RequirementUsage, derived as those PartUsages owned via StakeholderMemberships.
5. _References._ Implemented as _isReference_ meta-attribute of Usage. This attribute is nominally derived as `!isComposite`. However, `isReference` normally defaults to false (i.e., `isComposite = true`), except that it is always true (i.e.,`isComposite = false`) in the following cases:
    - For attributes and ports.
    - If `direction` is not null.
    - If `isEnd` is true.
    - If `owningFeatureMembership` is null (i.e., the Usage is not an `ownedFeature`).

**Library Updates**

1. _ScalarValues._ Updated the Number types so that Real specializes Complex, Rational specializes Real and Integer specializes Rational. Also updated the relevant functions packages to remove up-conversion functions that are no longer necessary.
2. _Items and Parts._ Added `Items::Item::subitems` and `Items::Item::subparts`. Renamed `Part::ports` to `Parts::portsOnPart`.
2. _Ports_ Updated Port to specialize Occurrence and `ports` to specialize `occurrences`. Added `Port::subports`.
3. _DecisionTransitionAction._ Renamed `Actions::DecisionTransition` to `DecisionTransitionAction`, specializing both Action and NonStateTransitionPerformance. DecisionTransitionAction is now properly used to type TransitionUsages used as "conditional Successions" in action models.
4. _StateTransitionAction._ Renamed `States::TransitionAction` to `StateTransitionAction`, which is used to type TransitionUsages used as transitions in state models. Added `Actions::TransitionAction` as a common abstract supertype of `DecisionTransitionAction` and `StateTransitionAction`.

**Not Covered**

A number of changes and new features in the 2021-06 metamodel are _not_ covered in this PR and will be implemented in subsequent PRs for this sprint per the issues below.

- ST6RI-387 Concrete syntax for assignment and control structures
   - This will also include implementing initial values for Features.
- ST6RI-404 Concrete syntax for use cases
- ST6RI-405 Concrete syntax for parallel states
- ST6RI-406 Dot notation for feature chains
- ST6RI-407 Revised concrete syntax for connections

### CODE REVIEW

**Comment by seidewitz** [comment]
@conradbock @rbarbau 

FYI

**Comment by seidewitz** [comment]
@himi @hpdekoning 
Unfortunately, review is needed on this (rather large) PR in short order, by the end of Monday (19 July). Otherwise we will likely need to move on and address problems if they are discovered later.

@ivan-gomes @manasbajaj 
The `SysML.uml` file on this branch should be ready for use in updating the API/services implementation to 2021-06.

**Comment by ivan-gomes** [comment]
It looks like `IncludeUseCaseUsage.includedUseCase` redefines `UseCaseUsage.includedUseCase` to be multiplicity of `1` compared to `UseCaseUsage`'s `*`. Is this intentional? While I understand that this is a valid redefinition it would be the first time the multiplicity has been narrowed in the metamodel afaik and causes typing issues with an OO modeling that uses collections for multiplicities greater than 1.

**Comment by seidewitz** [comment]
Oops! This is an unintentional name clash. `IncludeUseCaseUsage::includedUseCase` actually does _not_ redefine `UseCaseUsage::includedUseCase` -- it just has the same name as the inherited attribute, which is invalid, but not detected in the model by MagicDraw. I have pushed a commit to fix this by renaming `IncludeUseCaseUsage::includedUseCase` to `useCaseIncluded`.

**Comment by ivan-gomes** [comment]
> Oops! This is an unintentional name clash. `IncludeUseCaseUsage::includedUseCase` actually does _not_ redefine `UseCaseUsage::includedUseCase` -- it just has the same name as the inherited attribute, which is invalid, but not detected in the model by MagicDraw. I have pushed a commit to fix this by renaming `IncludeUseCaseUsage::includedUseCase` to `useCaseIncluded`.

Oops, I assumed redefinition from on the name collision. 😊 Thanks for the prompt fix though. Testing and then I'll leave a review.

**Review by ivan-gomes — APPROVED** [review]
lgtm

**Comment by conradbock** [comment]
Looks like the post-done changes in [ST6RI-386](https://openmbee.atlassian.net/browse/ST6RI-386) post-done comments haven't been made (I think you agreed with all but the most recent).  Were you going to make them later?

> Items and Parts. Added Items::Item::subitems and Parts::Part::subparts. Renamed Part::ports to Parts::portsOnPart.

What is the motivation for this renaming?  I assume it doesn't have semantics of as (the inverse of) UML's partWthPort. :)

**Review by himi — APPROVED** [review]
I quickly reviewed the PlantUML visualization code changes and they are simple and clear.  Thank you.

**Comment by seidewitz** [comment]
> Looks like the changes in [ST6RI-386](https://openmbee.atlassian.net/browse/ST6RI-386) post-done comments haven't been made (I think you agreed with all but the most recent). Were you going to make them later?

Thanks for reminding me about [ST6RI-386](https://openmbee.atlassian.net/browse/ST6RI-386). I have made some updates on this branch based on your remaining comments. See also my comment responding to you on ST6RI-386.

> > Items and Parts. Added Items::Item::subitems and Parts::Part::subparts. Renamed Part::ports to Parts::portsOnPart.
> 
> What is the motivation for this renaming? I assume it doesn't have semantics of as (the inverse of) UML's partWthPort. :)

This was simply to give the feature on Part a different name from `Ports::ports`, which it subsets.

**Pull request merged**
