### PR TITLE
ST6RI-551 Specializations to feature chains are not rendered (PlantUML)

### PR DESCRIPTION
**Pull request by himi**
When we subset or redefine features with feature chains, they were not shown because VPath did not care about such feature chains.  This fix renders such relationships.

### CODE REVIEW

**Comment by himi** [comment]
In the following example, 

```
package FeatureChainTest {
    part p1 {
        part p2 {
        	part p211 {
        		attribute a;	
        	}
        }
    }
    part p3 :> p1.p2;
    part p4 :> p3.p211;   
}
```

Still we have an issue in tree view without `SHOWINHERITED` style:

Screen Shot 2022-06-06 at 12 09 24 PM
(With `SHOWINHERITED`, it is rendered as:
Screen Shot 2022-06-06 at 12 09 54 PM
)

It is because inherited features to be referred are always rendered in compartment because the current visualizer cannot identify the relevant membership for such inherited features.  It requires more complex modifications to VTree and VCompartment.  I decided to defer it.    Interconnection view does not have such a problem because it does not explicitly render memberships.
Screen Shot 2022-06-06 at 12 12 04 PM

**Comment by himi** [comment]
I could come up with the way to get a membership from an element by looking up inherited memberships.  So the issue above was solved.

**Review by seidewitz — APPROVED** [review]
The result is a little odd, because you end up with two symbols for `P211`. But I think it is acceptable for now, and better than not having it rendered at all.

**Comment by himi** [comment]
@seidewitz previously, it was rendered as one symbol. But in this case, we could not distinguish p4 subsets `p3.p211` instead of `p2.p211`.  So the visualizer renders it twice but with `^` to show it is inherited.

**Pull request merged**
