### PR TITLE
ST6RI-648 Assembly-agnostic spatial modeling

### PR DESCRIPTION
**Pull request by conradbock**
Merged CompoundSpatialItem into SpatialItem as `componentItems`.  Under that:

- Redefined mrefs to ensure `componentItems` use the same ScalarMeasurementReference (unit) on each dimensions as the SpatialItem they are components of.
- Defaulted `transformation` to MeasurementReferences::`nullTransformation`, which is added to MeasurementReferences along with NullTransformation, a three dimensional CoordinateTransformation that places the target CoordinateFrame at the same position and orientation as the source CoordinateFrame.
- Updated geometry examples CarWithShapeAndCSG.sysml and VehicleGeometryAndCoordinateFrames.sysml to specialize SpatialItem instead of CompoundSpatialItem.

Made `componentItems` unordered, see dicussion on [ST4MD-450](https://openmbee.atlassian.net/browse/ST4MD-450).

### CODE REVIEW

**Review by seidewitz — APPROVED** [review]

**Comment by conradbock** [comment]
Forgot to finish updating the doc for `componentItems`, doing that now.

**Comment by hpdekoning** [comment]
By mistake I pushed [ST6RI-534 Added library MeasurementRefCalculations to support measure…] to this branch. Sorry, for the confusion. It is reverted now.

**Comment by conradbock** [comment]
Pushed update to `componentItems` doc.

**Review by hpdekoning — APPROVED** [review]
I approve as I have been fully in the loop with Conrad.

**Comment by seidewitz** [comment]
@conradbock

All set with this?

**Comment by conradbock** [comment]
All done!   Says there are conflicts, tho.

**Comment by seidewitz** [comment]
I'll handle the conflicts. They are from PR #406 for ST6RI-523 Extended Coordinate Transformation.

**Pull request merged**
